### ISSUE TITLE
BasicConsumeMessage throws an exception: connection closed unexpectedly

### ISSUE THREAD

**Issue by haolujun** [alanxz/SimpleAmqpClient#145]
Hi, when I used function “BasicConsumeMessage” to get a message from the queue, timeout is -1, the queue is empty.After About 15 minutes, this function throw an exception "connection closed unexpectedly"。So, I traced the code and found the function ”GetNextFrameFromBroker” in file "ChannelImpl.cpp"  occurred error， How do I solve this problem?

plus：
 Should I send some heartbeats to mq-server? And which function I should call ?

**Comment by alanxz** [comment]
This is likely due to the connection between your client and the broker being interrupted. You are correct in that AMQP-heartbeats should be used to detect interrupted connections and terminate the connection. Currently SimpleAmqpClient does not support heartbeats.

To recover from this you should destroy the Channel object and create a new one.
