### ISSUE TITLE
question: why i can't find the function"amqp_channel_open" called in this project source code?

### ISSUE THREAD

**Issue by guzuomuse** [alanxz/SimpleAmqpClient#201]
i'm digging into this excellent project
according to my understand. since this project wrappers the rabbitmq-c;
the function "amqp_channel_open" is used for create channel;
but why i can't any code in this SimpleAmqpClient reference to that function.
that's very strange!
i don't know how the SimpleAmqpClient to create channel without "amqp_channel_open". anyone can explain this for me?
thanks!

**Comment by alanxz** [comment]
Opening a channel is the same as any RPC-style method in AMQP. SimpleAmqpClient has its own routines for performing AMQP-RPCs by calling `amqp_send_method` and some fancy logic to read out the response so that it can detect when the response may block.

Code for channel open can be found starting: https://github.com/alanxz/SimpleAmqpClient/blob/6323892d3e8701489fb945f45aa877a7e2a0ce31/src/ChannelImpl.cpp#L114-L132

**Comment by guzuomuse** [comment]
👍 ,thank you!
