### ISSUE TITLE
make failing with : ‘TableValue(const int64_t&)’ is ambiguous at SimpleAMQClint/src/TableImpl.cpp:268:40

### ISSUE THREAD

**Issue by AmulMittal** [alanxz/SimpleAmqpClient#203]
Hello,
I,m trying to install SimpleAMQPClient on my ubuntu but make fails everytime I've checked for the dependencies but everything looks fine. 
Also, I tried installing other version of boost and unsinstalling DoOxygen but still I am getting the same error.

boost version 
amul@beast:~/Downloads/SimpleAMQClint/build$ dpkg -s libboost-dev | grep 'version'
Description: Boost C++ Libraries development files (default version)
 Boost version (currently 1.58).

Please find attached logs for cmake  and make commands.Please let me know how to resolve the issue or what can be possible workaround for the same 

[error.log](https://github.com/alanxz/SimpleAmqpClient/files/2360977/error.log)

System configurations - 
Processor - Intel® Core™ i3-4030U CPU @ 1.90GHz × 4 
Graphics - Intel® Haswell Mobile
OS type - 64-bit
Disk - 976.0 GB
Memory - 7.7 GiB

email for contact - amul.smart@gmail.com

**Comment by SimonLeeHub** [comment]
I have the same problem， do you fix that?

**Comment by alanxz** [comment]
@SimonLeeHub I haven't been able to reproduce this (it compiles without error on Ubuntu 20.04 with pre-packaged boost and gcc or clang compilers).

I suspect that this is due to either a bug in gcc or boost at those versions. The bug being either something to do with overload resolution in the compiler, or the definition of boost::uint64_t in the boost package not matching stdint.h's uint64_t.

What happens if you try compiling with the latest version of boost (say 1.71.0?).  Similarly does the bug also manifest itself when compiled with a newer version of Clang or GCC?

**Comment by SimonLeeHub** [comment]
@alanxz Thank you very much! Your suggestion is very helpful. I compile with boost-1.72.0, and it works. Thank you.
