### ISSUE TITLE
Declaring queue arguments seems ignored

### ISSUE THREAD

**Issue by grievertime** [alanxz/SimpleAmqpClient#244]
Hi, thanks for your work.
I'm trying to force a queue length to a max message count of 1, rejecting publish when full.

```c++
AmqpClient::Table queue_params;

queue_params.insert(std::pair<std::string, AmqpClient::TableValue>("x-max-length", AmqpClient::TableValue(1)));

queue_params.insert(std::pair<std::string, AmqpClient::TableValue>("x-overflow", AmqpClient::TableValue("reject-publish")));

AmqpClient::Channel::ptr_t instr = AmqpClient::Channel::Create("x.x.x.x");

instr->DeclareQueue("queue1", false, false, false, &queue_params);
```
Unfortunately the params seems to be ignored, i have the problem of a very fast producer and slow consumer and i'd like to block the producer until the message is consumed.

Running on docker with ubuntu 20.04, compiling with c++17 (hope this is not the issue)

**Comment by alanxz** [comment]
Make sure you're using the correct overload for [`Channel::DeclareQueue`](https://github.com/alanxz/SimpleAmqpClient/blob/c309e01815ab1f685db8ed1eb934dec137c55b06/src/SimpleAmqpClient/Channel.h#L476-L478).  (There should be 4 boolean parameters instead of 3, I suspect C++ is being helpful and converting &queue_params -> 'true').

**Comment by grievertime** [comment]
This was totally the issue, thank you very much!
