### ISSUE TITLE
Building with Visual Studio 2010

### ISSUE THREAD

**Issue by adambadura** [alanxz/SimpleAmqpClient#44]
I am trying to use the library on Windows (Windows 7 Professional) with Visual Studio 2010 and Boost 1.52 (current at the time of writing). And I get linking error for Boost.Chrono.

My procedure is following.
1. I am making a `git clone` into MinGW root folder. Thus I get `C:\MinGW\SimpleAmqpClient.git`.
2. Then I make a sibling directory for CMake: `C:\MinGW\SimpleAmqpClient.git-bin`.
3. There from command line I call `cmake "../SimpleAmqpClient.git"`
   - This fails because of missing references to Boost and rabbitmq-c.
4. Then again from command line I call `cmake -DBOOST_LIBRARYDIR="C:\Library\boost\boost_1_52_0\stage\Win32\lib" -DBOOST_INCLUDEDIR="C:\Library\boost\boost_1_52_0" -DRabbitmqc_INCLUDE_DIR="C:\Library\rabbitmq-c\Release\include" -DRabbitmqc_LIBRARY="C:\Library\rabbitmq-c\Release\lib\rabbitmq.1.lib" "../SimpleAmqpClient.git"`
   - For some reason specifying those values in first call to `cmake` fails with an error of some file missing. Apparently it it not willing to create then but the first call does create the file even thou the call fails.
5. This succeeds. Now I open the `SimpleAmqpClient.sln` file with Visual Studio IDE.
6. And there building the Win32.Debug configuration fails (on project `SimpleAmqpClient`). It fails with following message: `LINK : fatal error LNK1104: cannot open file 'libboost_chrono-vc100-mt-gd-1_52.lib'`.
   - There are also few Doxygen messages - just so that you know. (My Doxygen is 1.8.2.)

I played around with the project. Removing the dependency (generated by `cmake`) on Boost.Chrono from `Additional Dependencies` doesn't solve the issue. Because it is not this reference that fails.

The one that fails is automatic linking of Boost.Chrono itself. Note that it tries to link to `libboost_chrono-vc100-mt-gd-1_52.lib` (which is missing) rather than to `boost_chrono-vc100-mt-gd-1_52.lib` (which is there).

The `lib` prefix is used because preprocessor defines are set so. To skip the prefix the project would have to define (`_DLL` or `_RTLDLL`) and `BOOST_DYN_LINK` while apparently it doesn't. Not to mention that auto-linking would likely fail anyway since the project does not specify `Additional Library Directories` even thou I provide them to `cmake`.

Any help?

And by the way. How should I set things up so that `SimpleAmqpClient` in `Debug` builds with `rabbitmq-c` `Debug` while in `Release` it builds with `rabbitmq-c` `Release`? My `rabbitmq-c` is laid out so that in root directory I have subdirectories `Debug` and `Release` which contain complete installations of the library (`bin`, `include` and `lib`) for the given configuration.

**Comment by leogi22** [comment]
I am having trouble solving some CRT problems between my exe and the simpleamqpclient2.lib and boost and the rabbitmq.4.lib

I've used cmake/VS 2013 to build to rabbitmq.4.lib, using /MTd and producing a .lib

I then used cmake with the Boost_USE_STATIC_LIBS=ON flag (in cmake gui by adding Entry), then built the simpleamqpclient2.lib by linking against the boost 

libboost_chrono-vc120-mt-sgd-1_59.lib and 
libboost_system-vc120-mt-sgd-1_59.lib
rabbitmq.4.lib, using the /MTd CRT setting as well

It built fine.

I then linked my exe to the libs 
My exe uses the /MTd CRT setting.
I then load the the simpleamqpclient.h and run the exe

1 - AmqpClient::Channel::ptr_t channel = AmqpClient::Channel::Create("localhost");
2 - std::string myqueue("my_queue");
3 - myqueue = channel->DeclareQueue(std::string(""), false, false, false, true);

Every time I  get the following error:

dbgheap.c line 1424 
Expression pFirstBlock == phead

whenever line 2 is executed and the string is being deleted

which suggest a problem between the heaps. Based on what I could find, it has to do with the exe and the dll using different version of the CRT, which is not the case since everything is compiled using the /MTd option, and the libboost libraries are using statically. I did try different combinations of /MTd and /MDd. 
Please help!
Also, I'm new to the cmake utility, It appears that the solution it builds for the simpleamqpclient produces both a simpleamqpclient.lib and a simpleamqpclient.dll, and then I link in the exe to the simpleamqpclient2.lib. Is that correct?
